name: 'devpulse'
version: '0.1.0'
config-version: 2

profile: 'devpulse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  devpulse:
    staging:
      +materialized: view
      +schema: staging
    mart:
      +schema: mart
